title: Vish Sangale
tagline: Exploring the frontier of ML, Robotics, Neuroscience, and AI.
description: Staff Machine Learning Researcher at Meta. Exploring the frontier of ML, Robotics, Neuroscience, and AI.
url: "https://vishsangale.github.io"
baseurl: ""

collections:
  posts:
    output: true

permalink: /notes/:title/

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
