# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               The Shooting Star
tagline:             'Programmer, Amateur Astronomer and Photographer'
description:         'Personal website for sharing my projects, pictures and some blogs.'
url:                 http://vishsangale.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Vishwanath Sangale
  url:               https://twitter.com/vishsangale
  email:             vishsangale@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/vishsangale
twitter:			http://twitter.com/vishsangale
disqus:             vish

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
