#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Vishwanath Sangale

# Short bio or description (displayed in the header)
description: Agile Software Developer and Designer.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/2828667?v=3&u=4c0cf9ae6d211a1021f3e0039c1db942dd0c47ea&s=140

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: vishsangale@gmail.com
  facebook: rvishsangale
  flickr: vishsangale
  github: vishsangale
  instagram: vishsangale
  linkedin: vishsangale
  pinterest: 
  rss: on # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: vishsangale
  stackoverflow: users/3554264/vishsangale

# Your disqus shortname, entering this will enable commenting on posts
disqus: vishsangale

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://vishsangale.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
